### ISSUE TITLE
Use ampersand reference

### ISSUE THREAD

**Issue by jim-rosales** [Thomas1981Lang/prj-rev-bwfs-dasmoto#2]
When using symbols such as the ampersand or copy symbol, it's best to use their [character entity](https://developer.mozilla.org/en-US/docs/Glossary/Entity) reference. I usually don't have all the references memorized, so I use this [cheat sheet](https://dev.w3.org/html5/html-author/charref) to find the most common ones. 

In this case, you can see how GitHub highlights the ampersand in red. To fix this issue just replace the ampersand with `&amp;`

https://github.com/Thomas1981Lang/prj-rev-bwfs-dasmoto/blob/d5af3092072623e0c028ff7f36637d19e3fe21b9/Dasmotos_Art-Crafts/index.html#L5

**Comment by Thomas1981Lang** [comment]
Thanks for the hint and the link to the cheat sheet.
I changed the & in both places into &amp;
