### ISSUE TITLE
Fallback font

### ISSUE THREAD

**Issue by jim-rosales** [Thomas1981Lang/prj-rev-bwfs-dasmoto#4]
Whenever you use a specific font, it is best to include a generic fallback font just in case the browser cannot load your desired font. 

Here is an [example](https://gist.github.com/jim-rosales/5c6594497fee028550f7c84083d2a30f)of a CSS style using a fall back font. 

https://github.com/Thomas1981Lang/prj-rev-bwfs-dasmoto/blob/d5af3092072623e0c028ff7f36637d19e3fe21b9/Dasmotos_Art-Crafts/resources/css/index.css#L6

**Comment by Thomas1981Lang** [comment]
Thank you for that advice. 
I added the fallback.
